### ISSUE TITLE
US 0- Crear Landing

### ISSUE THREAD

**Issue by lsofi** [pgPilfs/pil-money-g3d-pil-money-g3d#31]
Como usuario quiero poder ver una pagina principal intuitiva para poder consultar los servicios ofrecidos y poder registrarme.
- [ US 0.1] Desarrollar Header de landing.
- [ US 0.2] Desarrollar Footer de landing.
- [ US 0.3] Desarrollar Content de landing.

**Comment by aylen916** [comment]
Me asigno [ US 0.1] Desarrollar Header de landing.
